CREATE DATABASE `AFASFA` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci;

CREATE TABLE infocontato (
  IDCONTATO INTEGER(10) UNSIGNED NOT NULL,
  NOME VARCHAR(60) NOT NULL,
  FOTO VARCHAR(150) NOT NULL,
  RECEBERINFORMACOES TINYINT(1) NOT NULL,
  CEP VARCHAR(10) NOT NULL,
  LOGRADOURO VARCHAR(50) NOT NULL,
  NUMERO INTEGER(10) UNSIGNED NOT NULL,
  COMPLEMENTO VARCHAR(20) NOT NULL,
  BAIRRO VARCHAR(30) NOT NULL,
  CIDADE VARCHAR(30) NOT NULL,
  UF CHAR(2) NOT NULL,
  TELEFONECEL DECIMAL(10,0) NOT NULL,
  TELEFONERES DECIMAL(10,0) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  SEXO CHAR(1) NOT NULL DEFAULT M,
  APELIDO VARCHAR(20) NOT NULL,
  PRIMARY KEY(IDCONTATO)
);

CREATE TABLE eventos (
  EVENTO INTEGER(10) UNSIGNED NOT NULL,
  DESCRICAO VARCHAR(60) NOT NULL,
  DATAEVENTO DATE NOT NULL,
  LOCALEVENTO VARCHAR(150) NOT NULL,
  FOTOINICIAL VARCHAR(100) NOT NULL,
  JAREALIZADO TINYINT(1) NOT NULL,
  APRESENTAR TINYINT(1) NOT NULL,
  RESERVADISPONIVEL TINYINT(1) NOT NULL,
  DATAMAXIMA DATE NOT NULL,
  VALORCONVITEA DECIMAL(10,2) NOT NULL,
  VALORCONVITEC DECIMAL(10,2) NOT NULL,
  OBSERVACAO TEXT NOT NULL,
  PRIMARY KEY(EVENTO)
);

CREATE TABLE projetos (
  PROJETO INTEGER(10) UNSIGNED NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL,
  FOTO VARCHAR(100) NOT NULL,
  DADOSDOPROJETO TEXT NOT NULL,
  ORDEMAPRESENTACAO INTEGER(11) NOT NULL,
  PRIMARY KEY(PROJETO)
);

CREATE TABLE pais (
  sigla CHAR(2) NOT NULL,
  nome VARCHAR(50) NOT NULL
);

CREATE TABLE assistencias (
  ASSISTENCIA INTEGER(10) UNSIGNED NOT NULL,
  DESCRICAO VARCHAR(60) NOT NULL,
  RESPONSAVEL VARCHAR(30) NOT NULL,
  PRIMARY KEY(ASSISTENCIA)
);

CREATE TABLE doacoes (
  DOACAO INTEGER(10) UNSIGNED NOT NULL,
  NOME VARCHAR(60) NOT NULL,
  DATADOACAO DATE NOT NULL,
  ITENS TEXT NOT NULL,
  DISPONIBILIDADE TEXT NOT NULL,
  OBSERVACAO TEXT NOT NULL,
  ESTADO CHAR(1) NOT NULL DEFAULT P,
  TELEFONERES DECIMAL(10,0) NOT NULL,
  TELEFONECEL DECIMAL(10,0) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(60) NOT NULL,
  BAIRRO VARCHAR(30) NOT NULL,
  PRIMARY KEY(DOACAO)
);

CREATE TABLE voluntarios (
  VOLUNTARIO INTEGER(10) UNSIGNED NOT NULL,
  APELIDO VARCHAR(20) NOT NULL,
  NACIONALIDADE CHAR(1) NOT NULL DEFAULT B,
  DATANASCIMENTO DATE NOT NULL,
  ESTADOORIGEM INTEGER(2) NOT NULL,
  CIDADEORIGEM VARCHAR(40) NOT NULL,
  HABILITADO TINYINT(1) NOT NULL,
  ESTADOCIVIL CHAR(1) NOT NULL,
  TRABALHA TINYINT(1) NOT NULL,
  ESCOLARIDADE VARCHAR(30) NOT NULL,
  PROFISSAO VARCHAR(40) NOT NULL,
  LOCALDETRABALHO VARCHAR(40) NOT NULL,
  COMOFICOUSABENDO VARCHAR(60) NOT NULL,
  TIPOVOLUNTARIO CHAR(1) NOT NULL DEFAULT D,
  QUALATIVIDADE VARCHAR(100) NOT NULL,
  QUADISPONIBILIDADE INTEGER(10) UNSIGNED NOT NULL,
  QUAISDIAS VARCHAR(7) NOT NULL,
  ACEITATERMO TINYINT(1) NOT NULL,
  TEMPODOVOLUNTARIO VARCHAR(100) NOT NULL,
  ESTADO CHAR(1) NOT NULL,
  IDCONTATO INTEGER(10) UNSIGNED NOT NULL,
  PAISORIGEM VARCHAR(30) NOT NULL,
  PRIMARY KEY(VOLUNTARIO),
  INDEX FK_Estado_Voluntario(ESTADOORIGEM),
  INDEX IDCONTATO(IDCONTATO)
);

CREATE TABLE usuarios (
  usuario INTEGER(10) NOT NULL,
  login VARCHAR(20) NOT NULL,
  senha VARCHAR(100) NOT NULL,
  administrador CHAR(1) NOT NULL DEFAULT N,
  IDCONTATO INTEGER(10) UNSIGNED NOT NULL,
  PRIMARY KEY(usuario),
  INDEX login(login)
);

CREATE TABLE dados_quantitativos (
  MESANO VARCHAR(6) NOT NULL,
  ASSISTENCIA INTEGER(10) UNSIGNED NOT NULL,
  QTDECRIANCASF INTEGER(10) UNSIGNED NOT NULL,
  QTDECRIANCASM INTEGER(10) UNSIGNED NOT NULL,
  QTDEADOLESCENTESF INTEGER(10) UNSIGNED NOT NULL,
  QTDEADOLESCENTESM INTEGER(10) UNSIGNED NOT NULL,
  QTDEADULTOSF INTEGER(10) UNSIGNED NOT NULL,
  QTDEADULTOSM INTEGER(10) UNSIGNED NOT NULL,
  QTDEFAMILIA INTEGER(10) UNSIGNED NOT NULL,
  DESCRICAO VARCHAR(40) NOT NULL,
  RESPONSAVEL VARCHAR(60) NOT NULL,
  PRIMARY KEY(MESANO, ASSISTENCIA),
  INDEX DADOS_QUANTITATIVOS_FKIndex1(ASSISTENCIA)
);

CREATE TABLE cidade (
  codigoestado SMALLINT(6) NOT NULL,
  nome VARCHAR(50) NOT NULL,
  INDEX fk_codigoestado_cidade(codigoestado)
);

CREATE TABLE estado (
  codigopais SMALLINT(6) NOT NULL,
  sigla CHAR(2) NOT NULL,
  nome VARCHAR(50) NOT NULL,
  INDEX fk_codigopais_estado(codigopais)
);


