 ALTER TABLE `voluntarios` CHANGE `USUARIOS_USUARIO` `VOLUNTARIO` INT( 10 ) UNSIGNED NOT NULL AUTO_INCREMENT  ;


ALTER TABLE `voluntarios` ADD PRIMARY KEY(`VOLUNTARIO`);


 ALTER TABLE `voluntarios` CHANGE `ESTADOORIGEM` `ESTADOORIGEM` INT(2) NOT NULL  ;