
CREATE DATABASE `AFASFA` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci;

use `AFASFA`;

CREATE TABLE ASSISTENCIAS (
  ASSISTENCIA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(60) NOT NULL,
  RESPONSAVEL VARCHAR(30) NOT NULL,
  PRIMARY KEY(ASSISTENCIA)
);

CREATE TABLE DADOS_QUANTITATIVOS (
  MESANO VARCHAR(6) NOT NULL,
  ASSISTENCIA INTEGER UNSIGNED NOT NULL,
  QTDECRIANCASF INTEGER UNSIGNED NULL,
  QTDECRIANCASM INTEGER UNSIGNED NULL,
  QTDEADOLESCENTESF INTEGER UNSIGNED NULL,
  QTDEADOLESCENTESM INTEGER UNSIGNED NULL,
  QTDEADULTOSF INTEGER UNSIGNED NULL,
  QTDEADULTOSM INTEGER UNSIGNED NULL,
  QTDEFAMILIA INTEGER UNSIGNED NULL,
  DESCRICAO VARCHAR(40) NOT NULL,
  RESPONSAVEL VARCHAR(60) NOT NULL,
  PRIMARY KEY(MESANO, ASSISTENCIA),
  INDEX DADOS_QUANTITATIVOS_FKIndex1(ASSISTENCIA)
);

CREATE TABLE DOACOES (
  DOACAO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(60) NULL,
  DATADOACAO DATE NULL,
  ITENS TEXT NOT NULL,
  DISPONIBILIDADE TEXT NOT NULL,
  OBSERVACAO TEXT NULL,
  ESTADO CHAR(1) NULL DEFAULT 'P',
  TELEFONERES NUMERIC(10) NOT NULL,
  TELEFONECEL NUMERIC(10) NULL,
  EMAIL VARCHAR(100) NULL,
  PRIMARY KEY(DOACAO)
);

CREATE TABLE EVENTOS (
  EVENTO INTEGER UNSIGNED NOT NULL,
  DESCRICAO VARCHAR(60) NOT NULL,
  DATAEVENTO DATE NOT NULL,
  LOCALEVENTO VARCHAR(150) NOT NULL,
  FOTOINICIAL VARCHAR(100) NULL,
  JAREALIZADO BOOL NULL,
  APRESENTAR BOOL NULL,
  RESERVADISPONIVEL BOOL NULL,
  DATAMAXIMA DATE NULL,
  VALORCONVITEA NUMERIC(10,2) NOT NULL,
  VALORCONVITEC NUMERIC(10,2) NOT NULL,
  OBSERVACAO TEXT NULL,
  PRIMARY KEY(EVENTO)
);

CREATE TABLE PROJETOS (
  PROJETO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(50) NULL,
  FOTO VARCHAR(100) NULL,
  DADOSDOPROJETO TEXT NULL,
  ORDEMAPRESENTACAO INTEGER NOT NULL,
  PRIMARY KEY(PROJETO)
);

CREATE TABLE USUARIOS (
  USUARIO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(10) NOT NULL,
  NOME VARCHAR(60) NULL,
  SENHA VARCHAR(10) NOT NULL,
  FOTO VARCHAR(150) NULL,
  RECEBERINFORMACOES BOOL NULL,
  CEP VARCHAR(10) NULL,
  LOGRADOURO VARCHAR(50) NULL,
  NUMERO INTEGER UNSIGNED NULL,
  COMPLEMENTO VARCHAR(20) NULL,
  BAIRRO VARCHAR(30) NULL,
  CIDADE VARCHAR(30) NULL,
  UF CHAR(2) NULL,
  TELEFONECEL NUMERIC(10) NULL,
  TELEFONERES NUMERIC(10) NULL,
  EMAIL VARCHAR(100) NULL,
  PRIMARY KEY(USUARIO)
);

CREATE TABLE VOLUNTARIOS (
  USUARIOS_USUARIO INTEGER UNSIGNED NOT NULL,
  NOME VARCHAR(60) NOT NULL,
  APELIDO VARCHAR(20) NOT NULL,
  NACIONALIDADE CHAR(1) NOT NULL DEFAULT 'B',
  DATANASCIMENTO DATE NOT NULL,
  ESTADOORIGEM VARCHAR(2) NOT NULL,
  CIDADEORIGEM VARCHAR(40) NOT NULL,
  HABILITADO BOOL NULL,
  ESTADOCIVIL CHAR(1) NULL,
  TRABALHA BOOL NULL,
  ESCOLARIDADE VARCHAR(30) NULL,
  PROFISSAO VARCHAR(40) NULL,
  LOCALDETRABALHO VARCHAR(40) NULL,
  COMOFICOUSABENDO VARCHAR(60) NULL,
  TIPOVOLUNTARIO CHAR(1) NULL DEFAULT 'D',
  QUALATIVIDADE VARCHAR(100) NULL,
  QUADISPONIBILIDADE INTEGER UNSIGNED NULL,
  QUAISDIAS INTEGER UNSIGNED NULL,
  ACEITATERMO BOOL NULL,
  TEMPODOVOLUNTARIO VARCHAR(100) NULL,
  ESTADO CHAR(1) NULL,
  INDEX VOLUNTARIOS_FKIndex1(USUARIOS_USUARIO)
);


